idf_component_register(SRCS "main.c" 
                            "bldc/bldc_servo.c"
                            "common/common.c"
                            "control/control.c"
                            "control/filter.c"
                            "control/humidificador.c"
                            "control/lut.c"
                            "ds18b20/ds18b20app.c"
                            "i2c/i2c_app.c"
                            "i2c/i2c_drv/ads1015.c"
                            "i2c/i2c_drv/ds1338.c"
                            "i2c/i2c_drv/sdp810.c"
                            "proc/fResp.c"
                            "uart/uartapp.c"
                            "mqtt/mqtt.c"
                            "uSD/usdApp.c" 
                            "uSD/usdDrv.c" 
                            "wifi/wifiDrv.c"
                            "wifi/wifiserver.c"
                        INCLUDE_DIRS "."
                        EMBED_FILES "wifi/favicon.ico" "wifi/upload_script.html")   